<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>comment</key>
    <string>
        TODO: language
         1. Add a bunch of HTML tags.  See the #block and #style sections.
         3. Correctly scope all the parser functions and their contents.
            This on will be complicated, as there are several: expr, if, etc.
         5. Get some kind of folding by heading (Not possible with TM1 rules).
         7. Make sure that illegal things are correctly scoped illegal.
            This is non-trivial, and has several parts
              - Bold/italic are based on brain-dead heuristics.  Also, we should
                scope as illegal when for instance a new heading starts
                before an italic has been closed.
              - Templates... these will be pretty tough as they are flexible.
         9. &lt;timeline&gt;&lt;/timeline&gt; tag.  Not sure this one is worth the effort

        10. Figure out a better scope for meta.function-call.  Infininight
            suggests entity.name.function.call, to be paralleled by
            entity.name.function.definition.  I am not completly sure I like
            that solution, but it is probably better than meta.function-call

        TODO snippents and commands
         2. Add a drop command (and keyboard shortcuts) for links/images
         3. Make sure all the preference items are sorted out, for instance
            smart typing pairs, indent patterns, etc.
         4. Command: big/small

        FINISHED:
         2. Add support for LaTeX math mode inside of &lt;math&gt;&lt;/math&gt; tags.
         1. Add a command for new list item.  This one is trivial
         6. Get the symbol list working on headings.  Trivial.
         8. &lt;gallery&gt;&lt;/gallery&gt; tag.  This one adds some complication, but
            is worth supporting.
         4. commands for bold/italic  (tbates)
         4. All lists scoped by type of list.  (tbates)
    </string>
    <key>fileTypes</key>
    <array>
        <string>mediawiki</string>
        <string>wikipedia</string>
        <string>wiki</string>
    </array>
    <key>keyEquivalent</key>
    <string>^~M</string>
    <key>name</key>
    <string>Mediawiki (ST2)</string>
    <key>patterns</key>
    <array>
        <dict>
            <key>include</key>
            <string>#block</string>
        </dict>
        <dict>
            <key>include</key>
            <string>#inline</string>
        </dict>
    </array>
    <key>repository</key>
    <dict>
        <key>block</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>^\s*(?i)(#redirect)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.control.redirect.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>\n</string>
                    <key>name</key>
                    <string>meta.redirect.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>((&lt;/?)(code|div|pre|span|font))</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(&gt;)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.tag.validhtml.mediawiki</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string> ?(&lt;)(source)[ \t]+(lang)(=)("[^"]+")(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.mediawiki</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.mediawiki</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>source: &lt;source lang="R"&gt;</string>
                    <key>end</key>
                    <string> ?(&lt;/)(source)(&gt;)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.tag.source.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#source-stuff</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string> ?(&lt;)(uml)(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string> ?(&lt;/)(uml)(&gt;)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>storage.type.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.definition.tag.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.tag.source.mediawiki</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(={1})(?!=)(?=.*\1\s*$)</string>
                    <key>comment</key>
                    <string>Match lines that begin &amp; end with  1 “=”: Mismatch "=" marked invalid.</string>
                    <key>end</key>
                    <string>\1\s*$\n?</string>
                    <key>name</key>
                    <string>markup.heading.1.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>={1}(=+\s*$)</string>
                            <key>name</key>
                            <string>invalid.illegal.extra-equals-sign.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(={2})(?!=)(?=.*\1\s*$)</string>
                    <key>comment</key>
                    <string>Match next heading</string>
                    <key>end</key>
                    <string>\1\s*$\n?</string>
                    <key>name</key>
                    <string>markup.heading.2.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>={2}(=+\s*$)</string>
                            <key>name</key>
                            <string>invalid.illegal.extra-equals-sign.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(={3})(?!=)(?=.*\1\s*$)</string>
                    <key>comment</key>
                    <string>Match next heading</string>
                    <key>end</key>
                    <string>\1\s*$\n?</string>
                    <key>name</key>
                    <string>markup.heading.3.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>={3}(=+\s*$)</string>
                            <key>name</key>
                            <string>invalid.illegal.extra-equals-sign.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(={4})(?!=)(?=.*\1\s*$)</string>
                    <key>comment</key>
                    <string>Match next heading</string>
                    <key>end</key>
                    <string>\1\s*$\n?</string>
                    <key>name</key>
                    <string>markup.heading.4.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>={4}(=+\s*$)</string>
                            <key>name</key>
                            <string>invalid.illegal.extra-equals-sign.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(={5})(?!=)(?=.*\1\s*$)</string>
                    <key>comment</key>
                    <string>Match next heading</string>
                    <key>end</key>
                    <string>\1\s*$\n?</string>
                    <key>name</key>
                    <string>markup.heading.5.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>={5}(=+\s*$)</string>
                            <key>name</key>
                            <string>invalid.illegal.extra-equals-sign.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>
                        A separator is made up of 4 or more -s alone on a
                        line by themselves.
                    </string>
                    <key>match</key>
                    <string>^-{4,}[ \t]*($\n)?</string>
                    <key>name</key>
                    <string>meta.separator.mediawiki</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^ (?=\s*\S)</string>
                    <key>comment</key>
                    <string>
                        Code blocks start with one space.  Wiki text and
                        html are still interpreted in MediaWiki, unlike in
                        mediawiki.
                    </string>
                    <key>end</key>
                    <string>^(?=[^ ])</string>
                    <key>name</key>
                    <string>markup.raw.block.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^([#:;])</string>
                    <key>comment</key>
                    <string>
                        need to scope nested lists
                          - need to cope with
                                definition lists (; :)
                            indented paragraphs, as used on talk pages (:)
                    </string>
                    <key>end</key>
                    <string>^(?!\1)</string>
                    <key>name</key>
                    <string>markup.list.numbered.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^([*])</string>
                    <key>comment</key>
                    <string>unordered list</string>
                    <key>end</key>
                    <string>^(?!\1)</string>
                    <key>name</key>
                    <string>markup.list.unnumbered.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#table</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#comments</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>^(?![\t ;*#:=&lt;]|----|$)</string>
                    <key>comment</key>
                    <string>
                        Anything that is not a code block, list, header, etc.
                        is a paragraph.
                    </string>
                    <key>end</key>
                    <string>^(?:\s*$|(?=[;*#:=&lt;]|----))</string>
                    <key>name</key>
                    <string>meta.paragraph.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>block_html</key>
        <dict>
            <key>comment</key>
            <string>
                The available block HTML tags supported are:
                  * blockquote, center, pre, div, hr, p
                  * tables: table, th, tr, td, caption
                  * lists: ul, ol, li
                  * definition lists: dl, dt, dd
                  * headers: h1, h2, h3, h4, h5, h6
                  * br
            </string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(&lt;math&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>0</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.section.embedded.tex.math</string>
                        </dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.math.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>source.tex.math</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>source.tex.math</string>
                    <key>end</key>
                    <string>((&lt;)/math&gt;)</string>
                    <key>name</key>
                    <string>meta.embedded.tex.math</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>text.tex.math</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>&lt;table[^&gt;]*&gt;</string>
                    <key>contentName</key>
                    <string>source.html</string>
                    <key>end</key>
                    <string>&lt;/table&gt;</string>
                    <key>name</key>
                    <string>meta.embedded.html.table</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>text.html</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;)(ref)(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.ref.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>&lt;ref&gt;content&lt;/ref&gt; TODO: Redundant with named tag</string>
                    <key>contentName</key>
                    <string>meta.reference.content.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/)(ref)(&gt;)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.ref.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.ref.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.name.mediawiki</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.ref.name.mediawiki</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>&lt;ref name="label"/&gt;</string>
                    <key>match</key>
                    <string>(&lt;)(ref) *((name) *(=) *([^&gt;]*))(/&gt;)</string>
                    <key>name</key>
                    <string>meta.reference.named.cite.mediawiki</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;)(ref) *((name) *(=) *([^&gt;]*))(&gt;)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.ref.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>entity.name.tag.name.mediawiki</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>string.quoted.ref.name.mediawiki</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>&lt;ref name="label"&gt;content&lt;/ref&gt;</string>
                    <key>contentName</key>
                    <string>meta.reference.content.labelled.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/ref&gt;)</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;gallery[^&gt;]*&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.ref.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>meta.gallery.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/gallery&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>begin</key>
                            <string>(?x)
                                ^(?!\s*\n)            # not an empty line
                                ( [ ]*(([Ff]ile|[Ii]mage)(:)) # spaces, image, colon
                                  ([^\[\]|]+)           # anything (filename)
                                  ((\|)([^\n]*))?        # pipe, anything (description)
                                  (?&lt;!\s)[ ]*           # spaces
                                )?
                            </string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>3</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.other.namespace.image.mediawiki</string>
                                </dict>
                                <key>4</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.colon.mediawiki</string>
                                </dict>
                                <key>5</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.other.wiki-link.image.mediawiki</string>
                                </dict>
                                <key>6</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                </dict>
                            </dict>
                            <key>end</key>
                            <string>\n</string>
                            <key>name</key>
                            <string>meta.item.gallery.mediawiki</string>
                            <key>patterns</key>
                            <array>
                                <dict>
                                    <key>begin</key>
                                    <string>^(?!\|)|(\|)</string>
                                    <key>beginCaptures</key>
                                    <dict>
                                        <key>1</key>
                                        <dict>
                                            <key>name</key>
                                            <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                        </dict>
                                    </dict>
                                    <key>contentName</key>
                                    <string>string.other.title.gallery.mediawiki</string>
                                    <key>end</key>
                                    <string>\n|(?=\|)</string>
                                    <key>patterns</key>
                                    <array>
                                        <dict>
                                            <key>include</key>
                                            <string>#inline</string>
                                        </dict>
                                    </array>
                                </dict>
                                <dict>
                                    <key>match</key>
                                    <string>\|</string>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                </dict>
                            </array>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>comments</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>&lt;!--</string>
                    <key>end</key>
                    <string>--\s*&gt;</string>
                    <key>name</key>
                    <string>comment.block.html.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>match</key>
                            <string>--</string>
                            <key>name</key>
                            <string>invalid.illegal.bad-comments-or-CDATA.html.mediawiki</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>entities</key>
        <dict>
            <key>comment</key>
            <string>
                Mediawiki supports Unicode, so these should not usually be
                necessary, but they do show up on pages from time to time.
            </string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>&amp;([a-zA-Z0-9]+|#[0-9]+|#x[0-9a-fA-F]+);</string>
                    <key>name</key>
                    <string>constant.character.entity.html.mediawiki</string>
                </dict>
                <dict>
                    <key>match</key>
                    <string>&amp;</string>
                    <key>name</key>
                    <string>invalid.illegal.bad-ampersand.html.mediawiki</string>
                </dict>
            </array>
        </dict>
        <key>inline</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.date-time.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.too-many-tildes.mediawiki</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>(~~~~~)(~{0,2})(?!~)</string>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>3 ~s for sig, 4 for sig + timestamp</string>
                    <key>match</key>
                    <string>~~~~?</string>
                    <key>name</key>
                    <string>constant.other.signature.mediawiki</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#link</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#style</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#table</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#template</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#block_html</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#comments</string>
                </dict>
            </array>
        </dict>
        <key>link</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>applyEndPatternLast</key>
                    <integer>1</integer>
                    <key>begin</key>
                    <string>(?x:
                        (\[\[)                         # opening brackets
                          ( [ ]*(([Ff]ile|[Ii]mage)(:)) # spaces, image, colon
                            ([^\[\]|]+)                # anything
                            (?&lt;!\s)[ ]*                # spaces
                          )
                    )</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.namespace.image.mediawiki</string>
                        </dict>
                        <key>5</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.fix_this_later.colon.mediawiki</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.wiki-link.image.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?x:
                          ((\|)[ ]*( [^\[\]|]+ )[ ]*)? # pipe, spaces, anything, spaces
                        (\]\])                         # closing brackets
                    )</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.fix_this_later.pipe.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>string.other.title.link.wiki-link.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.image.wiki.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.formatting.mediawiki</string>
                                </dict>
                                <key>3</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.frame.mediawiki</string>
                                </dict>
                                <key>4</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.alignment.mediawiki</string>
                                </dict>
                                <key>5</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.alignment-vertical.mediawiki</string>
                                </dict>
                                <key>6</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.numeric.image.width.mediawiki</string>
                                </dict>
                                <key>7</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.other.unit.image.size.mediawiki</string>
                                </dict>
                                <key>8</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.numeric.image.height.mediawiki</string>
                                </dict>
                                <key>9</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.size.mediawiki</string>
                                </dict>
                                <key>10</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.link.mediawiki</string>
                                </dict>
                                <key>11</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.other.wiki-link.mediawiki</string>
                                </dict>
                                <key>12</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.alt.mediawiki</string>
                                </dict>
                                <key>13</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.other.image.alt.mediawiki</string>
                                </dict>
                                <key>14</key>
                                <dict>
                                    <key>name</key>
                                    <string>keyword.control.image.css-class.mediawiki</string>
                                </dict>
                                <key>15</key>
                                <dict>
                                    <key>name</key>
                                    <string>constant.other.image.css-class.mediawiki</string>
                                </dict>
                                <key>16</key>
                                <dict>
                                    <key>name</key>
                                    <string>string.other.image.caption.mediawiki</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>(?x)
                                (\|)[ ]*
                                ( (thumbnail|thumb|frameless|frame|border)
                                 |(right|left|center|none)
                                 |(baseline|sub|super|top|text-top|middle|bottom|text-bottom)
                                 |([0-9]+)?(x?)([0-9]+)?(px)
                                 |(link=)([^|]+)?
                                 |(alt=)([^|]+)?
                                 |(class=)([^|]+)?
                                 |([^|\]]+)
                                )[ ]*
                            </string>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\|</string>
                            <key>name</key>
                            <string>punctuation.fix_this_later.pipe.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?x:
                    ({{)                       # opening brackets
                        ([Rr]edirect|subst:.*)   # redirect?
                        [ ]*                   # spaces
                        (\|)                   # pipe
                    )</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.redirect.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.wiki-link.redirect.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.pipe.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?x:
                            (([\|}]+)(\|)([\|}]+))?   #  from | to
                            ([^}]*)                   # anything
                            (}})                      # closing brackets
                    )</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>markup.underline.link.internal.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.pipe.mediawiki</string>
                        </dict>
                        <key>6</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.redirect.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.link.wiki.redirect.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?x:
                        (\[\[)                       # opening brackets
                          (:)?                       # colon to suppress image or category?
                          ((\s+):[^\[\]]*(?=\]\]))?  # a colon after spaces is invalid
                          [ ]*                       # spaces
                          ( (([^\[\]|]+)(:))?        # namespace
                            ([^\[\]|]+)(?&lt;!\s)[ ]*   # link name
                          )?
                    )</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>keyword.operator.wiki-link.suppress-image-or-category.mediawiki</string>
                        </dict>
                        <key>4</key>
                        <dict>
                            <key>name</key>
                            <string>invalid.illegal.whitespace.mediawiki</string>
                        </dict>
                        <key>7</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.namespace.mediawiki</string>
                        </dict>
                        <key>8</key>
                        <dict>
                            <key>name</key>
                            <string>punctuation.fix_this_later.colon.mediawiki</string>
                        </dict>
                        <key>9</key>
                        <dict>
                            <key>name</key>
                            <string>constant.other.wiki-link.mediawiki</string>
                        </dict>
                    </dict>
                    <key>end</key>
                    <string>(?x:
                          (\|[ ]*([^\[\]\|]+)[ ]*)?     # pipe, spaces, anything, spaces
                        (\]\])                         # closing brackets
                    )</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>string.other.title.link.wiki-link.mediawiki</string>
                        </dict>
                        <key>3</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.link.wiki.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>\[(\S+)\s*(?=[^\]]*\])</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>markup.underline.link.external.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>string.other.title.link.external.mediawiki</string>
                    <key>end</key>
                    <string>\]</string>
                    <key>name</key>
                    <string>meta.link.inline.external.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>match</key>
                    <string>((https?|ftp|file)://|mailto:)[-:@a-zA-Z0-9_.~%+/?=&amp;#]+(?&lt;![.?:])</string>
                    <key>name</key>
                    <string>markup.underline.link.external.mediawiki</string>
                </dict>
            </array>
        </dict>
        <key>source-stuff</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="python"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.python</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="ini"&gt;)</string>
                    <key>comment</key>
                    <string>INI plugin required</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.ini</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="javascript"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.js</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="c"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.c</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="actionscript"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.actionscript</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="applescript"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.applescript</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="asp"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.asp</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="dos"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.dosbatch</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="csharp"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.cs</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="cpp"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.c++</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="clojure"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.clojure</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="css"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.css</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="d"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.d</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="erlang"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.erlang</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="go"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.go</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="haskell"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.haskell</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="java"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.java</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="groovy"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.groovy</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="latex"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.latex</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="lisp"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.lisp</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="lua"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.lua</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="make"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.makefile</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="matlab"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.matlab</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="objc"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.objc</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="ocaml"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.ocaml</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="pascal"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.pascal</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="perl"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.perl</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="php"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.php</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="r"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.r</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="rails"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.ruby.rails</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="ruby"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.ruby</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="scala"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.scala</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="bash"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.shell</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="sql"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.sql</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="tsql"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.tsql</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="tcl"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.tcl</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="xml"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>text.xml</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="yaml"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>source.yaml</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(?&lt;=&lt;source lang="html5"&gt;)</string>
                    <key>end</key>
                    <string>(?=&lt;/source&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>text.html.basic</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>comment</key>
                    <string>unknown source</string>
                </dict>
            </array>
        </dict>
        <key>style</key>
        <dict>
            <key>comment</key>
            <string>
                TODO: Still need to add:
                  * font
                  * ruby, rb, rp, rt
                  * cite
                inline tags to this section, and make sure that the other
                tags can accept attributes in the tag opening, etc.  The
                current implementation is intended to be naive, but covering
                the majority of uses in mediawiki code.

                We also need to add mediawiki-specific tags:
                  * nowiki, noinclude, includeonly

            </string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>'''</string>
                    <key>end</key>
                    <string>'''</string>
                    <key>name</key>
                    <string>markup.bold.html.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>''</string>
                    <key>end</key>
                    <string>''(?!'[^'])</string>
                    <key>name</key>
                    <string>markup.italic.html.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(b|strong)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.bold.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.bold.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(i|em)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.italic.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.italic.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(s|strike)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.strikethrough.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.other.strikethrough.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(u)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.underline.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.underline.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(tt|code)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.raw.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.raw.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(big|small|sub|sup)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.other.inline-styles.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>style_in_link</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>'''</string>
                    <key>end</key>
                    <string>'''</string>
                    <key>name</key>
                    <string>markup.bold.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>''</string>
                    <key>end</key>
                    <string>''</string>
                    <key>name</key>
                    <string>markup.italic.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(b|strong)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.bold.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.bold.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(i|em)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.italic.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.italic.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(s|strike)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.strikethrough.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.other.strikethrough.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(u)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.underline.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.underline.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(tt|code)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.raw.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.raw.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>(&lt;(big|small|sub|sup)&gt;)</string>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.any.html.mediawiki</string>
                        </dict>
                    </dict>
                    <key>contentName</key>
                    <string>markup.other.inline-styles.html.mediawiki</string>
                    <key>end</key>
                    <string>(&lt;/\2&gt;)</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#style_in_link</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#comments</string>
                </dict>
            </array>
        </dict>
        <key>table</key>
        <dict>
            <key>patterns</key>
            <array>
                <dict>
                    <key>begin</key>
                    <string>^({\|)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.table.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>TODO: add styling capabilities</string>
                    <key>end</key>
                    <string>(^\|})</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.table.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>markup.other.table.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>meta.tag.inline.table.caption.mediawiki</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>variable.parameter.name.string.mediawiki</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>^(\|\+)[\t ]*(.*)$</string>
                            <key>name</key>
                            <string>meta.table.caption.mediawiki</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>^\|-</string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>meta.tag.inline.table.mediawiki</string>
                                </dict>
                            </dict>
                            <key>comment</key>
                            <string>TODO: allow selection of rows; move row up/down, etc.</string>
                            <key>end</key>
                            <string>^(?=\|-|^\|})</string>
                            <key>name</key>
                            <string>markup.other.table.row.mediawiki</string>
                            <key>patterns</key>
                            <array>
                                <dict>
                                    <key>include</key>
                                    <string>#inline</string>
                                </dict>
                            </array>
                        </dict>
                        <dict>
                            <key>captures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>meta.tag.inline.table.cellwall.mediawiki</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>string.other.table.cellcontents.mediawiki</string>
                                </dict>
                            </dict>
                            <key>match</key>
                            <string>(^\||\|\|) *([^\|]*) *</string>
                            <key>name</key>
                            <string>meta.table.cell.mediawiki</string>
                        </dict>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
        <key>template</key>
        <dict>
            <key>comment</key>
            <string>
                This repository item covers templates and parser functions.
            </string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.template.numeric.mediawiki</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>{{{[ ]*([0-9]+)[ ]*}}}</string>
                    <key>name</key>
                    <string>meta.template-parameter.mediawiki</string>
                </dict>
                <dict>
                    <key>captures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>variable.parameter.template.named.mediawiki</string>
                        </dict>
                    </dict>
                    <key>match</key>
                    <string>{{{[ ]*(.*?)[ ]*}}}</string>
                    <key>name</key>
                    <string>meta.template-parameter.mediawiki</string>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>({{)(?=[ ]*#)</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.template.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>meta.function-call.template.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>
                        Why oh why did mediawiki have to add these??
                    </string>
                    <key>end</key>
                    <string>(}})</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.template.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.template.parser-function.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#inline</string>
                        </dict>
                    </array>
                </dict>
                <dict>
                    <key>begin</key>
                    <string>({{)([^{}\|]+)?</string>
                    <key>beginCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.template.mediawiki</string>
                        </dict>
                        <key>2</key>
                        <dict>
                            <key>name</key>
                            <string>meta.function-call.template.mediawiki</string>
                        </dict>
                    </dict>
                    <key>comment</key>
                    <string>scope as meta.function-call as the closest thing to a template with parameters, etc.</string>
                    <key>end</key>
                    <string>(}})</string>
                    <key>endCaptures</key>
                    <dict>
                        <key>1</key>
                        <dict>
                            <key>name</key>
                            <string>meta.tag.inline.template.mediawiki</string>
                        </dict>
                    </dict>
                    <key>name</key>
                    <string>meta.template.mediawiki</string>
                    <key>patterns</key>
                    <array>
                        <dict>
                            <key>include</key>
                            <string>#comments</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>(\|)\s*(=)</string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.equals-sign.mediawiki</string>
                                </dict>
                            </dict>
                            <key>contentName</key>
                            <string>comment.block.template-hack.mediawiki</string>
                            <key>end</key>
                            <string>(?=[|}])</string>
                        </dict>
                        <dict>
                            <key>begin</key>
                            <string>(\|)(([^{}\|=]+)(=))?</string>
                            <key>beginCaptures</key>
                            <dict>
                                <key>1</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.pipe.mediawiki</string>
                                </dict>
                                <key>2</key>
                                <dict>
                                    <key>name</key>
                                    <string>variable.parameter.template.mediawiki</string>
                                </dict>
                                <key>3</key>
                                <dict>
                                    <key>name</key>
                                    <string>punctuation.fix_this_later.equals-sign.mediawiki</string>
                                </dict>
                            </dict>
                            <key>contentName</key>
                            <string>meta.value.template.mediawiki</string>
                            <key>end</key>
                            <string>(?=[|}])</string>
                            <key>patterns</key>
                            <array>
                                <dict>
                                    <key>include</key>
                                    <string>#inline</string>
                                </dict>
                                <dict>
                                    <key>include</key>
                                    <string>#block</string>
                                </dict>
                            </array>
                        </dict>
                        <dict>
                            <key>match</key>
                            <string>\|</string>
                            <key>name</key>
                            <string>punctuation.fix_this_later.pipe.mediawiki</string>
                        </dict>
                    </array>
                </dict>
            </array>
        </dict>
    </dict>
    <key>scopeName</key>
    <string>text.html.mediawiki</string>
    <key>uuid</key>
    <string>6AF21ADF-316A-47D1-A8B6-1BB38637DE9A</string>
</dict>
</plist>
